### ISSUE TITLE
Requirements setup

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-onion-team6#1]
[정보보호실습.pdf](https://github.com/KAIST-IS521/2018s-onion-team6/files/1829028/default.pdf)

**Comment by soohun-kim** [comment]
파일 리뷰하고 아직 부족한 요구사항들이 있으니 잘 정의해보도록 합시다.

**Comment by soohun-kim** [comment]
+
도커사용하기.

**Comment by sunnyeo** [comment]
유저 개인키 docker container로 옮겨지게

**Comment by sunnyeo** [comment]
메신저 시작할때 터미널로 PGP 키 패스워드 입력받기

**Comment by sunnyeo** [comment]
[onion routing.pdf](https://github.com/KAIST-IS521/2018s-onion-team6/files/1832026/onion.routing.pdf)
