### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-onion-team6#2]
Docker를 사용할 환경 구축하기.
Dockerfile 세팅에 필요한 패키지들 생각해보기.

**Comment by k1rh4** [comment]
최종 commit 을 통하여 docker 셋팅을 완료하였습니다. 
패키지 모두 설치가 되었고 부팅시 attach 를하지 않고 바로 onion 메신져가 부팅됩니다.
close 시키겠습니다.
