### ISSUE TITLE
Protocol design issues

### ISSUE THREAD

**Issue by soohun-kim** [KAIST-IS521/2018s-onion-team6#3]
필요한 프로토콜 관련 이슈
1. Broadcast
2. Send message

**Comment by sunnyeo** [comment]
client 만

**Comment by sunnyeo** [comment]
github ID가 왜 필요하지?

**Comment by sunnyeo** [comment]
서버 없이 클라이언트만으로 구성하기로 결정

**Comment by sunnyeo** [comment]
1. Broadcast : client의 up/down flag, github id

**Comment by sunnyeo** [comment]
2. Send message
2-1. 1st message : send user, recv user, msg length
2-2. others : data

**Comment by sunnyeo** [comment]
3. message를 받으면 ack를 보낼지

**Comment by sunnyeo** [comment]
2. 모든 메시지를 전송하기 전에는 길이 정보를 먼저 보내야한다.

**Comment by k1rh4** [comment]
마지막에 보니 설계에서 크게 틀어지지 않고 잘 완성된것 같네요. 모두 수고 많으셨습니다.
