### ISSUE TITLE
About Dockerfile and scripts

### ISSUE THREAD

**Issue by DaramG** [KAIST-IS521/2018s-onion-team6#32]
Your Dockerfile is too slow because it does not use ubuntu mirror server in korea.
And when I execute `2_container_docker.sh`,  it just exits.
I think it should be running forever because of `sleep infinity` in `start.sh`

**Comment by k1rh4** [comment]
최종본에서 /bin/sh 대신 도커를 실행과 동시에 직접 onion 바이너리를 실행하도록 셋팅하겠습니다.

**Comment by k1rh4** [comment]
commit c56ef34b148db59cb0eacd413d8d5e73d6ac3763 에서 수정하였습니다.
