### ISSUE TITLE
Final Comment from the professor and TAs

### ISSUE THREAD

**Issue by DaramG** [KAIST-IS521/2018s-onion-team6#46]
프로젝트를 진행하시느라 수고 많으셨습니다. 프로젝트와 발표에 대한 교수님과 조교들의 코멘트입니다.

- 발표 시간은 질의응답 포함 17분 50초로 잘 지켜졌습니다.
- 동영상 데모는 매우 좋았으나, 동영상을 설명하는 중에 어디를 봐야할지 잘 모르겠고 설명과 동영상이 매칭이 전혀 되지 않았습니다. 동영상 설명에 대한 연습이 좀 더 필요해 보입니다.
- Threat model을 활용하고 SDL을 활용하여 보안성을 강조한 것은 좋았으나, 메신저가 secure하다는 것을 이야기하려면 좀 더 정량적인 metric이 필요해 보입니다.
- Selling point를 "보안"에 초점을 맞추기보다는 다른 부분에 맞췄으면 더 좋았을 것 입니다.
- Security를 고려하여 여러 필터를 넣고, 구현 후 취약점이 없는지 코드리뷰를 진행한 부분이 좋았습니다.
- Onion routing의 개념 및 design 부분의 시각화가 잘 되었습니다.
- Extra 기능이 없다는 점이 약간 아쉬웠습니다.

**Comment by k1rh4** [comment]
평가하느라 고생하셨습니다. bb

**Comment by sunnyeo** [comment]
comment 감사합니다!
