### ISSUE TITLE
Can steal someone's message

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team6#52]
I can steal someone's message cause there is no ID verification.
Real githubA is first person. But third person login with `githubA`.
Then confidentiality is broken.

![1](https://user-images.githubusercontent.com/26449129/38493962-08ba3184-3c2f-11e8-9677-b2fdf73629f1.png)

![2](https://user-images.githubusercontent.com/26449129/38493965-0b8836fe-3c2f-11e8-8cf2-432e8ddf20fb.png)

If you want to increase the probability, you can increase the number of clients.

**Comment by sunnyeo** [comment]
Yes! we need to identify same id.

**Comment by soohun-kim** [comment]
In [Activity3-0319.md](https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0319.md), There is an assumption **Each item in the list consists of a client's Github ID and the IP address used by that client. For simplicity, we assume that the list always contains the correct information: every client in the list should be up and reachable, and we do not consider any spoofing attack on this list.**. 
However, you are right. I think it needs to be handled that mapping Github-ID onto PubKey

**Comment by zanywhale** [comment]
@soohun-kim Thank you for feedback! :)
