### ISSUE TITLE
Path injection and kill the client using githubID

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team6#54]
The second client's githubID is `../`.
If `../` sends a message, the client dies.

![image](https://user-images.githubusercontent.com/26449129/38499352-34b30a6e-3c42-11e8-9a0d-fd548072f7d4.png)

![image](https://user-images.githubusercontent.com/26449129/38499364-43639164-3c42-11e8-90bb-ee1346eb4693.png)

And the others cannot detect abnormal termination.

![image](https://user-images.githubusercontent.com/26449129/38499391-5f8af83c-3c42-11e8-8a10-ad76c136b898.png)

**Comment by sunnyeo** [comment]
Thanks for reporting bug!
