### ISSUE TITLE
User account issue

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-onion-team6#7]
demo에서 최소 5개가 필요하고
저희가 github email로 pgp key를 가져오는 구조이니

추가적인 user가 필요할 듯 하네요

**Comment by k1rh4** [comment]
private 키들을 각 독커에서 따로 적용시킬수 있도록 코딩을 해야하는지 고민중임.

**Comment by k1rh4** [comment]
수훈이가 만들어준 private key 6개를 전부 git 에 올렸고 도커에 옵션에 따라 
private key가 다르게 설정되어 도커가 돌아가도록 셋팅함.
