### ISSUE TITLE
Implementation references

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-onion-team6#9]
프로그램 구현시 참고하면 좋을만한 사이트들
##### Naming Conventions
- https://google.github.io/styleguide/cppguide.html#Naming
- http://geosoft.no/development/cppstyle.html#Naming%20Conventions
##### GPG
- https://www.gnupg.org/documentation/manuals/gpgme/

**Comment by k1rh4** [comment]
고생많으셨습니다.
